version: 2
project_name: ratatoskr
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/ratatoskr
    binary: ratatoskr
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^chore(deps):"
      - "^ci:"
